# Generated by Django 4.2.1 on 2023-06-19 18:28

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image_delete_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='media',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
