# Generated by Django 4.2.1 on 2023-09-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
