# Generated by Django 4.2.1 on 2023-06-09 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photosapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='photos',
            name='type',
            field=models.CharField(choices=[('V', 'Video'), ('P', 'Photo')], default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
