# Generated by Django 4.2.1 on 2023-06-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photosapp', '0002_photos_date_photos_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='type',
        ),
    ]
