# Generated by Django 4.2.1 on 2023-06-12 16:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photosapp', '0003_remove_photos_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
