# Generated by Django 4.2.1 on 2023-06-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photosapp', '0004_alter_photos_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='image',
            new_name='media',
        ),
    ]
