# Generated by Django 4.2.1 on 2023-09-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photosapp', '0006_photos_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='user',
        ),
    ]
